// UI pass: every screen as the player sees it (page screenshots include the DOM overlay).
await frames(20);
await shotPage('01_menu');
game.ui.showNewGame();
await frames(3);
await shotPage('02_newgame');
game.ui.showSettings('menu');
await frames(3);
await shotPage('03_settings_graphics');
document.querySelectorAll('.tabs button')[2].click();
await frames(3);
await shotPage('04_settings_controls');
game.ui.showMenu();
game.ui.showMultiplayer();
await frames(3);
await shotPage('05_multiplayer');
game.ui.showMenu();
await start({ start: 'garage' });
await frames(30);
await shotPage('06_hud_garage');
game.pause();
await frames(3);
await shotPage('07_pause');
game.resume();
game.input.locked = true;
game.openJournal();
await frames(3);
await shotPage('08_journal');
game.stats.notes.push('home'); game.ui.showNote('home', true);
await frames(3);
await shotPage('09_note');
game.resume();
game.input.locked = true;
game.player.hurt(1000, 'thirst');
await wait(2500);
await frames(3);
await shotPage('10_death');
